on: push
jobs:
  build-esp32-c3-devkitm-1:
    name: Build binary for esp32-c3-devkitm-1
    runs-on: ubuntu-22.04
    steps:
      - name: Adjust firmware filename
        run: mv .pio/build/esp32-c3-devkitm-1/firmware.bin firmware-esp32dev.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-esp32-c3-devkitm-1.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
